### ISSUE TITLE
Seqlengths of GRange contains NA values!

### ISSUE THREAD

**Issue by huipan1973** [Roleren/uORFomePipe#1]
The code I run:
df.rfp <- read.experiment("Abby_Mouse_Ribo-seq")
df.rna <- read.experiment("Abby_Mouse_RNA-seq")
find_uORFome("/n/jobspace/bbcore/schaffer_rpf_abby_min6/two_batches/uORFome", organism = "Mus musculus",
             df.rfp = df.rfp, df.rna = df.rna, df.cage = NULL, biomart = NULL)

The error message:
--------------------------------------
Making training data from CDS and trailers (3' UTRs):
--------------------------------------
Finding Ribo-seq features for cds
/n/jobspace/bbcore/schaffer_rpf_abby_min6/two_batches/bam/rpf/pshifted/20210125_Index_1_JS8600_S9_R1_001_UMIremoved_pshifted.ofst
Error: BiocParallel errors
  1 remote errors, element index: 1
  15 unevaluated and other errors
  first remote error:
Error in covRleFromGR(x, weight = weight, ignore.strand = ignore.strand): Seqlengths of x contains NA values!

**Comment by huipan1973** [comment]
I actually got "Making training data from CDS and trailers (3' UTRs)" done. But have a another error then:

Training data on CDS and 3' UTRs finished
--------------------------------------
Creating sequence features from ORFs
--------------------------------------
Finding Ribo-seq features for uORFs
/n/jobspace/bbcore/schaffer_rpf_abby_min6/two_batches/bam/rpf/pshifted/20210125_Index_1_JS8600_S9_R1_001_UMIremoved_pshifted.ofst
Error: BiocParallel errors
  1 remote errors, element index: 1
  15 unevaluated and other errors
  first remote error:
Error in covRleFromGR(x, weight = weight, ignore.strand = ignore.strand): Seqlengths of x contains NA values!
In addition: Warning messages:
1: call dbDisconnect() when finished working with a connection
2: useNames = NA is deprecated. Instead, specify either useNames = TRUE or useNames = TRUE.
> traceback()
7: stop(.error_bplist(res))
6: .bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM,
       BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
5: bplapply(seq(length(paths)), function(x, grl, fiveUTRs, threeUTRs,
       cds, startRegion, paths, paths.rna) {
       message(paths[[x]])
       X <- paths[[x]]
       Y <- paths.rna[[x]]
       style <- seqlevelsStyle(grl)
       RNA <- if (!is.null(Y)) {
           fimport(Y, style)
       }
       else NULL
       weight.RNA <- 1L
       if (!is.null(RNA)) {
           if (!is.null(mcols(RNA)$score))
               weight.RNA <- "score"
       }
       ORFik:::allFeaturesHelper(grl, RFP = fimport(X, style), RNA = RNA,
           tx, fiveUTRs, cds, threeUTRs, faFile = NULL, riboStart = 26,
           riboStop = 34, sequenceFeatures = FALSE, grl.is.sorted = TRUE,
           weight.RFP = "score", weight.RNA = weight.RNA, st = startRegion)
   }, grl = grl, fiveUTRs = fiveUTRs, threeUTRs = threeUTRs, cds = cds,
       startRegion = startRegion, paths = paths, paths.rna = paths.rna,
       BPPARAM = BPPARAM)
4: bplapply(seq(length(paths)), function(x, grl, fiveUTRs, threeUTRs,
       cds, startRegion, paths, paths.rna) {
       message(paths[[x]])
       X <- paths[[x]]
       Y <- paths.rna[[x]]
       style <- seqlevelsStyle(grl)
       RNA <- if (!is.null(Y)) {
           fimport(Y, style)
       }
       else NULL
       weight.RNA <- 1L
       if (!is.null(RNA)) {
           if (!is.null(mcols(RNA)$score))
               weight.RNA <- "score"
       }
       ORFik:::allFeaturesHelper(grl, RFP = fimport(X, style), RNA = RNA,
           tx, fiveUTRs, cds, threeUTRs, faFile = NULL, riboStart = 26,
           riboStop = 34, sequenceFeatures = FALSE, grl.is.sorted = TRUE,
           weight.RFP = "score", weight.RNA = weight.RNA, st = startRegion)
   }, grl = grl, fiveUTRs = fiveUTRs, threeUTRs = threeUTRs, cds = cds,
       startRegion = startRegion, paths = paths, paths.rna = paths.rna,
       BPPARAM = BPPARAM)
3: getGeneralRiboFeatures(df.rfp, df.rna, orfs, preName = ifelse(mode ==
       "CDS", "verify", ""), BPPARAM = BPPARAM)
2: makeTrainingAndPredictionData(df.rfp, df.rna, organism = organism,
       mode = mode, max.artificial.length = max.artificial.length,
       features = features, requiredActiveCds = requiredActiveCds,
       BPPARAM = BPPARAM)
1: find_uORFome("/n/jobspace/bbcore/schaffer_rpf_abby_min6/two_batches/uORFome",
       organism = "Mus musculus", df.rfp = df.rfp, df.rna = df.rna,
       df.cage = NULL, biomart = NULL)

**Comment by huipan1973** [comment]
I think the error is from:

orfs <- uORFomePipe:::getUorfsInDb(mode = mode)

To checj, I run 
orfs <- uORFomePipe:::getUorfsInDb(mode = "uORF")
orfs has no seqlengths info

seqinfo: 31 sequences from an unspecified genome; no seqlengths

**Comment by Roleren** [comment]
Well impressive investigation I would say. Yes, you are right,ORFik (my core back end package) is now updated so much that uorfomePipe is not functional as of now. To fix it I would just need to ensure seqlevels are defined for the saved uorf object in uorfomePipe, should be a small fix. What you do is add seqinfo argument during creation of object. Either try to do it and send me a Pull request, or I will get to it later. 

Just a note that I am working on a newer model and for cross validation with other methods, I highly advice another package called Ribcode, but it is more cumbersome to get large datasets through. It also does not capture short uorfs. 

If you have not seen it yet, also test out our web interface which we are working on now called [Ribocrypt.org](https://Ribocrypt.org), it support almost all public riboseq out there (over 10 thousand samples)

**Comment by huipan1973** [comment]
Thank you for the prompt response. I would wait for you to fix it. In the meantime, I will look into Ribcode and Ribocrypt.org.

**Comment by huipan1973** [comment]
Hi, are there any updates on fixing the bugs?

**Comment by Roleren** [comment]
Not yet, on holiday, but I might have some time tomorrow to check it out :)

**Comment by Roleren** [comment]
One thing first, this might be a case if you have outdated ORFik.  Can you ORFik devel and test? run devtools::install_github("Roleren/ORFik")
Then restart R(important!) and run uORFomePipe again. It might be something fixed earlier :)

**Comment by huipan1973** [comment]
I installed  ORFik from git-hub. I still got the same error.

**Comment by Roleren** [comment]
This is now fixed (from October 10th), let me know if there is anything else.
